## **Decision Trees**

A decision tree is a flowchart-like structure in which each internal node represents a “test” on an attribute (e.g. whether a coin flip comes up heads or tails), each branch represents the outcome of the test, and each leaf node represents a class label (decision taken after computing all attributes).

By [Muhammad Huzaifa Shahbaz](https://www.linkedin.com/in/mhuzaifadev)

## **Importing libraries**


In [0]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix

## **Dataset Loading**

We will load data from the csv dataset

In [0]:
data = pd.read_csv(".\iris_data.csv")

## **Features Extraction**

To apply a classifier on this data, we need to extract features and target data and split it into test and train.

In [0]:
features = data[["SepalLength","SepalWidth","PetalLength","PetalWidth"]]
targets = data.Class

feature_train, feature_test, target_train, target_test = train_test_split(features,targets)

## **Finding an Optimal Value**

In [41]:
param_grid = {'max_depth': np.arange(1,10)}

tree = GridSearchCV(DecisionTreeClassifier(), param_grid)
fit_tree = tree.fit(feature_train, target_train)
tree_predictions = fit_tree.predict_proba(feature_test)[:,1]
print(fit_tree.best_params_)

{'max_depth': 7}


## **Training the Model**

We will use Decision Trees Classifier for training the model.

In [0]:
model = DecisionTreeClassifier(criterion='entropy',max_depth=7)
fit_model = model.fit(feature_train, target_train)

predictions = fit_model.predict(feature_test)

## **Printing an Error Matrix and Accuracy Score**

In [45]:
print(confusion_matrix(target_test,predictions))
print(accuracy_score(target_test,predictions))

[[13  0  0]
 [ 0 11  0]
 [ 0  1 13]]
0.9736842105263158
